Alertmessage : Alert pop up message from antd added #360 done
RamakrushnaBiswal/PlayCafe pull request #376
Opened 2024-10-21 11:10 UTC by VinayLodhi1712

Alertmessage : Alert pop up message from antd added #360 done.

https://github.com/user-attachments/assets/c905016c-ee8d-47b9-b1da-ed006637f669

2024-10-21 16:31 UTC, RamakrushnaBiswal requested changes

2024-10-21 16:31 UTC, RamakrushnaBiswal commented on backend/index.js
> +const errorMiddleware = require("./middlewares/errrorMiddleware"); // Corrected typo
@VinayLodhi1712 correct the speling

2024-10-21 16:31 UTC, RamakrushnaBiswal commented on frontend/src/components/Pages/Login.css
> +  /* Success message line animation */
don't use css files use tailwinf instead @VinayLodhi1712

2024-10-21 16:31 UTC, RamakrushnaBiswal commented on frontend/src/components/Pages/Login.jsx
>  const Login = () => {
@VinayLodhi1712 here alsp

2024-10-22 09:43 UTC, VinayLodhi1712 commented
@RamakrushnaBiswal Sir now you can check plz.

2024-10-22 14:51 UTC, RamakrushnaBiswal approved these changes

2024-10-22 14:52 UTC, merged