Add Event Booking APIs
RamakrushnaBiswal/PlayCafe pull request #378
Opened 2024-10-21 16:35 UTC by haseebzaki-07

fixes #363 

This PR adds necessary routes and controllers for a user to book any event, get his all event bookings.
Updated the schema of user and events so that a user can be associated with multiple events also the events can be associated by multiple users.
![Screenshot 2024-10-21 215741](https://github.com/user-attachments/assets/e839b0d9-a755-4cc3-ad28-591e9d2c0490)
![Screenshot 2024-10-21 215916](https://github.com/user-attachments/assets/6b81a45c-db7f-4ab1-93b6-db466121d3cc)

Upadated the method of delete route from "get" to "delete" because it was a bug also associated "/:id" for the specific event to be deleted.

![Screenshot 2024-10-21 214529](https://github.com/user-attachments/assets/05f50749-c2ed-411b-bfd0-1ef5135aed89)

2024-10-21 16:40 UTC, RamakrushnaBiswal requested changes

2024-10-21 16:40 UTC, RamakrushnaBiswal commented on backend/.env.example
> -GOOGLE_CLIENT_ID=your_google_client_id
why did you delete @haseebzaki-07

2024-10-21 16:40 UTC, RamakrushnaBiswal commented on backend/models/events.model.js
> -const { string } = require("zod");
@haseebzaki-07 is required or not

2024-10-21 16:55 UTC, haseebzaki-07 commented
hey @RamakrushnaBiswal made the necessary changes and brought back the .env.example

2024-10-22 14:54 UTC, RamakrushnaBiswal approved these changes

2024-10-22 14:55 UTC, merged